#!/usr/bin/env bash
# Script that sets up the web server - web-01

# Updating the apt-get repositories
sudo apt-get update

# Installing NGINX
sudo apt-get install -y nginx

# Starting nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo ufw enable -y

# Changing ownership to my current user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 777 /var/www

# Creating a backup for default page of nginx
cp /var/www/html/index.nginx-debian.html /var/www/index.nginx-debian.html.backup

# Change the content of the default page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart Nginx
sudo service nginx restart
