#!/usr/bin/env bash
# This script is displaying a list of currently running processes.
# 
# Requirements:
#	- Must show all processes, for all users, including those which might not have a TTY
#	- Display in a user-oriented format
# 	- Show process hierarchy
#
# But this script only displays the lines containing bash word, allowing you to easily get the PID
# of you bash process
#
# Rewuirements:
# 	- You cannot use pgrep
# 	- The third line of your script must be # shellcheck disable=SC2009
# shellcheck disable=SC2009
ps -aux --forest | grep bash
