#!/usr/bin/env bash
# This script displays the content of the file "/etc/passwd"
#
# Format:
# 	The user USERNAME is part of the GROUP_ID gang, lives 
# 	in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's 
# 	place is protected by the passcode PASSWORD, more info 
# 	about the user here: USER ID INFO

FILE="/etc/passwd"

while IFS=':' read -ra fields; do
	echo "The user ${fields[0]} is part of the ${fields[3]} gang, lives in the ${fields[5]} and rides ${fields[6]}. ${fields[2]}'s place is protected by the passcode ${fields[1]}, more info about the user here: ${fields[4]}"
done < $FILE

