#!/usr/bin/env bash
# This script displays the content of the file "/etc/passwd"
#
# Format:
# 	The user USERNAME is part of the GROUP_ID gang, lives 
# 	in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's 
# 	place is protected by the passcode PASSWORD, more info 
# 	about the user here: USER ID INFO

IFS=':'
while read -r user pass uid gid username_f homedir loginshell; do
      echo "The user $user is part of the $gid gang, lives in $homedir and rides $loginshell. $uid's place is protected by the passcode $pass, more info about the user here: $username_f"
done </etc/passwd
