#!/usr/bin/env bash
# This script is printing "Best School" 10 times,
# but on the 9th iteration it will also print "Hi"

count=1;

while [ "$count" -le 10 ]
do
	echo "Best School"
	
	if [ "$count" -eq 9 ]
	then
		echo "Hi"
	fi

	((count++))
done
