#!/usr/bin/env bash
# This script is printing the files in the current working directory
# Requirements:
# 	-- It must list the content of the current directory
#	-- It must be in a list format
# 	-- Where only the part of the name after the first dash is displayed

for i in *; do
	echo "$i" | cut -d '-' -f 2-
done
